### ISSUE TITLE
Add “absolute number of doses” increments rule

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#320]
To do:

- [x] find a good name
- [x] one for number of doses 
	- [x] e.g. up to dose y, then you can increase x dose levels
- [x] one for number of DLTs
	- [x] e.g. up to y DLTs so far, you can increase x dose levels
- [x] add classes and methods
- [x] add tests

**Comment by PuzzledFace** [comment]
It looks like validation is common between IncrementsAbsolute and IncrementsRelative  (and between IncrementsAbsoluteDLT and IncrementsRelativeDLT).  I'm not sure what your policy is for sharing common validation code, so I've simply copied and edited the existing "Relative" code so that it works for IncrementsAbsolute.  There is scope for creating wrapper functions that call the shared validation, if this is desired.

**Comment by danielinteractive** [comment]
Thanks @PuzzledFace , let's have a look at the details of this once you have the (draft) PR up.

**Comment by Puzzled-Face** [comment]
These new classes has already been added to `main`:
- Rules-class.R lines 699-796
- Rules-methods.R lines 1096-1178
- Rules-validity lines 214-248

Test also exist in the appropriate files.

There seems to be nothing to do.  Will close this issue.
