### ISSUE TITLE
Design ordinal CRM model

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#324]
Idea: We don't only record here 0/1 DLT outcomes, but instead DLT outcome on an ordinal scale, e.g. 0/1/2/3/4 toxicity levels.

To do:

- [x] Add design Rmd file under `design` folder
- [x] Describe statistical model and "theory" about it
	- [x] Also do a short literature search to see what is published on this already
- [x] Add prototype code: 
	- [x] Data
	- [x] Model
	- [ ] Increment rules
	- [ ] NextBest
	- [ ] etc. what is needed.

**Comment by wwojciech** [comment]
Hi @PuzzledFace - I would be happy to work with you on this issue. I think we technically can be both assigned to this.

**Comment by PuzzledFace** [comment]
@wwojciech Happy to have you aboard!  I've just created [a branch](https://github.com/Roche/crmPack/tree/324-design-ordinal-crm-model) with a first draft of the design document.  Feel free to comment.

**Comment by wwojciech** [comment]
HI @PuzzledFace I checked your comments and just wanted to sync with you on this, so that we can find something final for @danielinteractive. Would you be having some time to discuss it?

**Comment by wwojciech** [comment]
After the initial theory about oCRM was agreed in #372, we now proceed to the prototype implementation phase. Here are the topics raised by @PuzzledFace:

As I implement the design for ordinal CRM described in #372, I have realised that the changes required are more far reaching than @wwojciech and I anticipated.  Currently,

1. `h_jags_add_dummy` uses `assert_class(object, "Data")`.  I believe this should be `assert_class(object, "DataOrdinal")`.
2.  The assertion in `h_jags_get_model_inits` should allow `init` to be a closure in `.LogisticLogNormOrd`.
3. **_Most seriously_**.  `alpha[j] ~ dnorm(meanAlpha[j], precAlpha[j]) T(, alpha[j-1])` is valid JAGS syntax, but not valid R syntax.  This means that the existing approach of using `h_jags_write_model` to write the *body* of `model@priormodel` or `model@datamodel` to a temporary file will not work.  Similarly, introducing a dependency on `truncnorm` means the truncation can be written as `alpha[j] ~ dtruncnorm(meanAlpha[j], precAlpha[j], b=meanAlpha[j-1])`, but this is not valid JAGS syntax.  The approach I have taken is to make `h_jags_write_model` a generic.  The existing code works for all models apart from the new `.LogisticLogNormOrd` class and new variant for `.LogisticLogNormOrd`.  
4. Loops over `yCategories` should [I think] be from `2` to `length(yCategories)` and not any other variation.  Since R indexes from 1 but the design document indexes from 0, there is some ambiguity here.  We need to define the mapping from R-index to alpha-suffix.
5.  `ParamsLogNormal` class to allow for dimensions other than 2.  

Perhaps we need new slots, `jags_prior_model` and `jags_data_model`, say, which default to the body of the corresponding existing slot but which will allow for models whose specification in R and JAGS are different.

**Comment by danielinteractive** [comment]
Thanks @wwojciech and @PuzzledFace - since I think we need a bit more discussion on the class structure, can we please park this for now?
We can discuss when I am back from vacation in 2 weeks.

**Comment by PuzzledFace** [comment]
In the design document, the implementation of `priormodel` is inconsistent with the `y` slot of the `DataOrdinal` class.  `priormodel` states `y[i, j] ~ dbern(p[i, j])`, which is correct: `y` is a **_matrix of Bernoulli indicator flags_** `y[i, j] == 1` iff the `i`th subject reports an AE of category `j` or greater, and `0` otherwise.  

Conversely, `DataOrdinal` defines `y = "integer"` with prototype `y = integer()`, in other words an **_array of integers_** with `y[i] == j` where `j` is the highest AE category reported by subject `i`.  The conversion between the two formats is simple, but I'm not sure how best to handle it in the `crmPack` ecosystem.

**Comment by PuzzledFace** [comment]
Another thought: should the number of toxicity categories be an attribute of the *data* (as is currently proposed) or the *model*?  Logically, I think it should be an attribute of the model, but making it an attribute of the *data* may make it easier to implement.

**Comment by danielinteractive** [comment]
@PuzzledFace I think it is an attribute of the data, as it also refers to the data collection and interpretation, e.g. for descriptive statistics rather than model based analysis
