### ISSUE TITLE
Factor out `is.na(dose)` logic from `stopTrial` generic function into separate Stopping rule

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#583]
To do:

- [ ] Add unit tests for all `Stopping` classes to check that they can deal with `NA` dose values
- [x] Simplify the  `stopTrial` generic function
	- [x] see https://github.com/Roche/crmPack/blob/main/R/Rules-methods.R#L1796
	- [x] cut the block from line 1799 to line 1809 so that we have a standard generic
- [x] Add a new `Stopping` class `StoppingMissingDose`
	- [x] this should stop when the dose produced by the `NextBest` rule is `NA` 
	- [x] docs
	- [x] test
- [ ] Add references to the class from the relevant `NextBest` classes that can produce `NA`
- [ ] Add a paragraph to the migration vignette explaining this change and highlighting for which `NextBest` classes this rule needs to be added

**Comment by danielinteractive** [comment]
@0liver0815 fyi

**Comment by 0liver0815** [comment]
@danielinteractive, I started to work on adding checks to the stopping functions. I think that it is first necessary to simplify the `stopTrial` generic function, as `NA` is otherwise not passed to the individual stopping function and unit tests can not be set up.
After removing the proposed lines from `stopTrial` generic function, the `stopTrial` generic function fails when passing `dose = NA` to the function:

```
  my_data <- h_get_data()
  my_model <- h_get_logistic_kadane()
  my_samples <- mcmc(my_data, my_model, h_get_mcmc_options(samples = 1000, burnin = 1000))
  stopping <- StoppingMTDCV(target = 0.3, thresh_cv = 50)
  result <- stopTrial(
    stopping = stopping,
    dose = NA,
    samples = my_samples,
    model = my_model,
    data = my_data
  )

```
with the the following error message.
```
Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘stopTrial’ for signature ‘"StoppingMTDCV", "logical", "Samples", "LogisticKadane", "Data"’
```
I am stuck here. I tried to set `NA` to `0` which works. I am not sure why 
```
 standardGeneric("stopTrial")
```
is not able to handle `NA`.

**Comment by danielinteractive** [comment]
Thanks @0liver0815 , can you try with `dose = NA_real_` when calling `stopTrial`? Or just have a line in the generic function definition that forces `dose <- as.numeric(dose)`

**Comment by 0liver0815** [comment]
`dose = NA_real_` works. So the `nextBest` methods should pass `dose = NA_real_`?

**Comment by danielinteractive** [comment]
Yep, let's do like this for now for these tests
